# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/toshiba/betelgeuse/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
 $(LOCAL_PATH)/proprietary/etc/firmware/nvavp_os_00001000.bin:system/etc/firmware/nvavp_os_00001000.bin \
 $(LOCAL_PATH)/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
 $(LOCAL_PATH)/proprietary/etc/firmware/nvavp_os_e0000000.bin:system/etc/firmware/nvavp_os_e0000000.bin \
 $(LOCAL_PATH)/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
 $(LOCAL_PATH)/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
 $(LOCAL_PATH)/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
 $(LOCAL_PATH)/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
 $(LOCAL_PATH)/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
 $(LOCAL_PATH)/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
 $(LOCAL_PATH)/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
 $(LOCAL_PATH)/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
 $(LOCAL_PATH)/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
 $(LOCAL_PATH)/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
 $(LOCAL_PATH)/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
 $(LOCAL_PATH)/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
 $(LOCAL_PATH)/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
 $(LOCAL_PATH)/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
 $(LOCAL_PATH)/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
 $(LOCAL_PATH)/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
 $(LOCAL_PATH)/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
 $(LOCAL_PATH)/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
 $(LOCAL_PATH)/proprietary/lib/libnvos.so:system/lib/libnvos.so \
 $(LOCAL_PATH)/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
 $(LOCAL_PATH)/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
 $(LOCAL_PATH)/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
 $(LOCAL_PATH)/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
 $(LOCAL_PATH)/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
 $(LOCAL_PATH)/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
 $(LOCAL_PATH)/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
 $(LOCAL_PATH)/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
 $(LOCAL_PATH)/proprietary/lib/libnvcamerahdr.so:system/lib/libnvcamerahdr.so \
 $(LOCAL_PATH)/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
 $(LOCAL_PATH)/proprietary/lib/libtf_crypto_sst.so:system/lib/libtf_crypto_sst.so \
 $(LOCAL_PATH)/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
 $(LOCAL_PATH)/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
 $(LOCAL_PATH)/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
 $(LOCAL_PATH)/proprietary/lib/hw/gralloc.tegra3.so:system/lib/hw/gralloc.tegra.so \
 $(LOCAL_PATH)/proprietary/lib/hw/hwcomposer.tegra3.so:system/lib/hw/hwcomposer.tegra.so
